# Generated by Django 5.0.2 on 2024-03-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('service_description', models.TextField(max_length=255)),
                ('hourly_rate', models.IntegerField(verbose_name='Rate')),
                ('is_available', models.BooleanField(default=True)),
                ('total_providers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ReviewandRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True)),
                ('review', models.CharField(blank=True, max_length=1000)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='service')),
            ],
            options={
                'verbose_name': 'ReviewAndReview',
            },
        ),
    ]
