# Generated by Django 5.0.2 on 2024-03-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_rating_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
