# Generated by Django 5.0.2 on 2024-04-08 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('body', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_key', models.CharField(max_length=500)),
                ('device_name', models.CharField(max_length=200)),
                ('is_loggedin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificationss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('body', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('notification_type', models.CharField(max_length=50)),
                ('is_positive', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('rece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationstoreceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationsbyuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
