# Generated by Django 5.0.2 on 2024-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_announce_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationss',
            name='time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
