name: bookme
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev; suitable for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.8
  http: ^1.1.2
  hydrated_bloc: ^9.1.3
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  pin_code_fields: ^8.0.1
  responsive_grid: ^2.4.4
  smooth_page_indicator: ^1.1.0
  photo_view: ^0.14.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  awesome_snackbar_content: ^0.1.3
  geolocator: ^10.1.0
  location: ^5.0.3
  geocoding: ^2.1.1
  get: ^4.6.6
  flutter_phone_direct_caller: ^2.1.1
  datetime_picker_formfield: ^2.0.1
  google_nav_bar: ^5.0.6
  redacted: ^1.0.11
  flutter_map: ^6.1.0
  flutter_map_marker_popup: ^6.1.2
  url_launcher: ^6.2.4
  hidden_drawer_menu: ^3.0.1
  khalti: ^2.0.0
  # fluttertoast: ^8.2.4
  flash: ^3.1.0
  web_socket_channel: ^2.4.0
  connectivity_bloc: ^0.0.3
  flutter_map_cancellable_tile_provider: ^2.0.0
  khalti_flutter: ^3.0.0
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  rxdart: ^0.27.7
  flutter_local_notifications: ^16.3.3
  flutter_timezone: ^1.0.8
  device_info_plus: ^9.1.2
  iconly: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  favorite_button: ^0.0.4
  fl_chart: ^0.67.0
  jiffy: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
flutter_native_splash:
    color: "#42a5f5"
    image: assets/splash/logopreview.png
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/splash/logopreview.png"
  min_sdk_android: 21 
flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/
    - assets/imges/
    - assets/loginsignup/
    - assets/splash/
    - assets/images/
    - assets/onboarding/onboardingfirst.png
    - assets/images/bid/
    - assets/no_connection/no_animation.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
    
