# Generated by Django 5.0.2 on 2024-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_groupName', models.CharField(default=0, max_length=20)),
                ('sender', models.CharField(default='', max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
